CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

CREATE TABLE brands (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NULL,
    CONSTRAINT pk_brands PRIMARY KEY (id)
);

CREATE TABLE categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    image text NULL,
    parent_id bigint NULL,
    disabled boolean NOT NULL,
    published boolean NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE provinces (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);

CREATE TABLE sellers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NULL,
    account_number character varying(30) NULL,
    account_bank_name character varying(50) NULL,
    CONSTRAINT pk_sellers PRIMARY KEY (id)
);

CREATE TABLE users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NULL,
    password text NULL,
    first_name character varying(255) NULL,
    last_name character varying(255) NULL,
    national_code character varying(10) NULL,
    security_stamp text NULL,
    email_address character varying(255) NULL,
    mobile_number character varying(255) NULL,
    type integer NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE cities (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    province_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    is_center boolean NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id),
    CONSTRAINT fk_cities_provinces_province_id FOREIGN KEY (province_id) REFERENCES provinces (id) ON DELETE CASCADE
);

CREATE TABLE products (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NULL,
    description text NULL,
    brand_id bigint NOT NULL,
    characteristics text NULL,
    properties text NULL,
    image_list text NULL,
    thubmnail text NULL,
    seller_id bigint NULL,
    disabled boolean NOT NULL,
    published boolean NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_brands_brand_id FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE CASCADE,
    CONSTRAINT fk_products_sellers_seller_id FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE RESTRICT
);

CREATE TABLE refresh_tokens (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    token text NULL,
    expires timestamp without time zone NOT NULL,
    created timestamp without time zone NOT NULL,
    created_by_ip character varying(255) NULL,
    revoked timestamp without time zone NULL,
    revoked_by_ip character varying(255) NULL,
    replaced_by_token text NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_activation_codes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    code integer NOT NULL,
    issue_time timestamp without time zone NOT NULL,
    expire_time timestamp without time zone NOT NULL,
    CONSTRAINT pk_user_activation_codes PRIMARY KEY (id),
    CONSTRAINT fk_user_activation_codes_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE addresses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NULL,
    user_id bigint NOT NULL,
    city_id bigint NOT NULL,
    postal_code character varying(10) NULL,
    details text NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    disabled boolean NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_cities_city_id FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE CASCADE,
    CONSTRAINT fk_addresses_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_category_categories_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_category_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE product_prices (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    characteristic_values text NULL,
    price numeric NOT NULL,
    discount_price numeric NOT NULL,
    CONSTRAINT pk_product_prices PRIMARY KEY (id),
    CONSTRAINT fk_product_prices_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE product_quantities (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    characteristic_values text NULL,
    quantity integer NOT NULL,
    CONSTRAINT pk_product_quantities PRIMARY KEY (id),
    CONSTRAINT fk_product_quantities_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE wishlists (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT pk_wishlists PRIMARY KEY (id),
    CONSTRAINT fk_wishlists_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlists_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    check_out_data timestamp without time zone NULL,
    total_price numeric NOT NULL,
    state integer NOT NULL,
    address_id bigint NULL,
    track_no text NULL,
    deliverer_no text NULL,
    send_date timestamp without time zone NULL,
    approximate_delivery_date timestamp without time zone NULL,
    actual_delivery_date timestamp without time zone NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_addresses_address_id FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE shopping_carts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id text NULL,
    user_id bigint NULL,
    product_price_id bigint NOT NULL,
    count integer NOT NULL,
    date_created timestamp without time zone NOT NULL,
    CONSTRAINT pk_shopping_carts PRIMARY KEY (id),
    CONSTRAINT fk_shopping_carts_product_prices_product_price_id FOREIGN KEY (product_price_id) REFERENCES product_prices (id) ON DELETE CASCADE,
    CONSTRAINT fk_shopping_carts_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE order_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_price_id bigint NOT NULL,
    order_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric NOT NULL,
    final_price numeric NOT NULL,
    characteristic_values text NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_orders_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product_prices_product_price_id FOREIGN KEY (product_price_id) REFERENCES product_prices (id) ON DELETE RESTRICT
);

CREATE TABLE payments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    pay_token text NULL,
    unique_id text NULL,
    amount numeric NOT NULL,
    register_date timestamp without time zone NOT NULL,
    reference_number character varying(100) NULL,
    tracking_number character varying(100) NULL,
    state integer NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT fk_payments_orders_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX ix_addresses_city_id ON addresses (city_id);

CREATE INDEX ix_addresses_user_id ON addresses (user_id);

CREATE INDEX ix_categories_parent_id ON categories (parent_id);

CREATE INDEX ix_cities_province_id ON cities (province_id);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);

CREATE INDEX ix_order_items_product_price_id ON order_items (product_price_id);

CREATE INDEX ix_orders_address_id ON orders (address_id);

CREATE INDEX ix_orders_user_id ON orders (user_id);

CREATE INDEX ix_payments_order_id ON payments (order_id);

CREATE INDEX ix_product_category_category_id ON product_category (category_id);

CREATE INDEX ix_product_prices_product_id ON product_prices (product_id);

CREATE INDEX ix_product_quantities_product_id ON product_quantities (product_id);

CREATE INDEX ix_products_brand_id ON products (brand_id);

CREATE INDEX ix_products_seller_id ON products (seller_id);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE INDEX ix_shopping_carts_product_price_id ON shopping_carts (product_price_id);

CREATE INDEX ix_shopping_carts_user_id ON shopping_carts (user_id);

CREATE INDEX ix_user_activation_codes_user_id ON user_activation_codes (user_id);

CREATE INDEX ix_wishlists_product_id ON wishlists (product_id);

CREATE INDEX ix_wishlists_user_id ON wishlists (user_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20200911180748_InitPgsql', '3.1.7');

